"""Init migratio

Revision ID: 12d0dbb3378e
Revises: 27cee31bbd65
Create Date: 2024-03-24 00:56:57.354559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12d0dbb3378e'
down_revision = '27cee31bbd65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('movie_url', sa.String(), nullable=True))
    op.drop_column('sessions', 'movie_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('movie_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('sessions', 'movie_url')
    # ### end Alembic commands ###
