"""new update

Revision ID: f1489f361d48
Revises: 9a196be06dc1
Create Date: 2024-03-21 23:18:41.122017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1489f361d48'
down_revision = '9a196be06dc1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('sessions', 'movie_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'movie_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('sessions', 'user_id')
    # ### end Alembic commands ###
